language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
env:
    - DJANGO_PACKAGE="Django>=1.6,<1.7"
    - DJANGO_PACKAGE="Django>=1.7,<1.8"
    - DJANGO_PACKAGE="Django>=1.8,<1.9"

matrix:
  exclude:
  - python: "2.6"
    env: DJANGO_PACKAGE="Django>=1.7,<1.8"
  - python: "2.6"
    env: DJANGO_PACKAGE="Django>=1.8,<1.9"

install:
    - pip install $DJANGO_PACKAGE --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors unittest2; fi
script: python setup.py test
