language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
env:
    - DJANGO_PACKAGE="Django>=1.7,<1.8"
    - DJANGO_PACKAGE="Django>=1.8,<1.9"
    - DJANGO_PACKAGE="Django<1.10"

matrix:
  exclude:
  - python: "3.2"
    env: DJANGO_PACKAGE="Django<1.10"
  - python: "3.3"
    env: DJANGO_PACKAGE="Django<1.10"

install:
    - pip install --pre $DJANGO_PACKAGE
script: python setup.py test
